language: csharp
mono:
   - latest
install:
   - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
   - dnvm upgrade
   - dnu restore
script:
   - cd /home/travis/build/asizikov/github-status/src/GitHub.Status.Service.Tests
   - dnx test -parallel none
